services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pm
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: pm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pm -d pm"]
      interval: 2s
      timeout: 2s
      retries: 20
  

  migrate:
    build: .
    environment:
      DATABASE_URL: postgres://pm:pm@db:5432/pm?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/app/migrate"]
    restart: "no"
  

  api:
    build: .
    environment:
      ADDR: ":4000"
      DATABASE_URL: postgres://pm:pm@db:5432/pm?sslmode=disable
      SHUTDOWN_TIMEOUT: 10s
    ports:
      - "4000:4000"
    depends_on:
      migrate:
        condition: service_completed_successfully